name: CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: dotnet build tunit50-test.csproj
